export const vaisseauDePierreTracks = [
  {
    id: 'tr1',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Musik glaz',
    duration: '1:54',
  },
  {
    id: 'tr2',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Digoradur',
    duration: '3:17',
  },
  {
    id: 'tr3',
    albumId: 'le-vaisseau-de-pierre',
    name: 'L\'Abordage de l\'Avelenn - Les Matins de chagrin',
    duration: '4:36',
  },
  {
    id: 'tr4',
    albumId: 'le-vaisseau-de-pierre',
    name: 'With a Bing-tow-row-row',
    duration: '2:28',
  },
  {
    id: 'tr5',
    albumId: 'le-vaisseau-de-pierre',
    name: 'L\'Ouverture du chantier - Sonnerezh koz - Quiemboi',
    duration: '5:20',
  },
  {
    id: 'tr6',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Gavotten nevez war sujet mouilc\'hi tromilio',
    duration: '2:50',
  },
  {
    id: 'tr7',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Un soir à Tréhoët',
    duration: '3:36',
  },
  {
    id: 'tr8',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Klemnou ha meleudi',
    duration: '3:38',
  },
  {
    id: 'tr9',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Cantic war sujet an anaon',
    duration: '3:45',
  },
  {
    id: 'tr10',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Chant des anciens',
    duration: '4:30',
  },
  {
    id: 'tr11',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Musik gwenn',
    duration: '1:57',
  },
  {
    id: 'tr12',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Le Plus Dur Métier',
    duration: '3:25',
  },
  {
    id: 'tr13',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Les Préparatifs du déménagement',
    duration: '2:50',
  },
  {
    id: 'tr14',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Kimiad eur paour kaez den oblijet da guitad e vro',
    duration: '2:25',
  },
  {
    id: 'tr15',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Les Guerriers d\'une nuit',
    duration: '3:39',
  },
  {
    id: 'tr16',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Histoire du bateau blanc changé en goéland',
    duration: '3:56',
  },
  {
    id: 'tr17',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Kan bale ar re varo',
    duration: '7:21',
  },
  {
    id: 'tr18',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Gwerz inimaginabl war disparti lestr a vaen',
    duration: '4:15',
  },
  {
    id: 'tr19',
    albumId: 'le-vaisseau-de-pierre',
    name: 'Les Lambeaux de l\'enfance',
    duration: '4:27',
  },
  {
    id: 'tr20',
    albumId: 'le-vaisseau-de-pierre',
    name: 'L\'En dro vert',
    duration: '3:44',
  }
];
